language: java

sudo: required

# there is no openjdk8
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

after_success:
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true --debug
